@startjson

{
    "users": [
        {
            "address_2": "000F",
            "next_user_2": "0020H",
            "first_game_2": "0037h",
            "type_1": 0,
            "active_1": 1,
            "name_size_1": 11,
            "name_n": "3344112111301",
            "password_size_1": 3,
            "password_n": "123",
            "games": [
                {
                    "address_2": "0037h",
                    "next_game_2": "0040h",
                    "points_2": "100d",
                    "time_2": "100d",
                    "level_1": 1
                },
                {
                    "address": "0040h",
                    "next_game_2": 0,
                    "points_2": "0d",
                    "time": "120d",
                    "level_1": 2
                }
            ]
        },
        {
            "address_2": "0020H",
            "next_user_2": "0030H",
            "first_game_2": 0,
            "type_1": 1,
            "active_1": 1,
            "name_size_1": 11,
            "name_n": "2244112111301",
            "password_size_1": 3,
            "password_n": "123",
            "games": 0
        },
        {
            "address_2": "0030H",
            "next_user_2": 0,
            "first_game_2": 0,
            "type_1": 2,
            "active_1": 1,
            "name_size_1": 11,
            "name_n": "4444112111301",
            "password_size_1": 3,
            "password_n": "123",
            "games": 0
        }
    ]
}

@endjson